config/routes.rb
Rails.application.routes.draw do
  resources :projects, param: :slug
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' } 
  resources :delivery_boys do 
    member do
      get :cancel_order
      get 'deliverd_order',to: 'delivery_boys#deliverd_order'
    end
  end
  resources :orders do
    member do
      get :cancel_order
      get 'deliverd_order',to: 'orders#deliverd'
      post 'assign_order',to: 'orders#assign'
    end
  end
  resources :posts
  resources :authors
  resources :author_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  resources :comments
  resources :products do
    collection do
      get 'batch_operation'
    end
    member do
      get 'remove_description'
    end
  end
  resources :varients
end

app/models/delivery_boy.rb
class DeliveryBoy < ApplicationRecord
  has_many :orders, before_add: :assign_boy
  def assign_boy(order)
    order.delivery_status = "assign"
  end
end

app/controllers/delivery_boys_controller.rb
class DeliveryBoysController < ApplicationController
  before_action :set_delivery_boy, only: [:show, :edit, :update, :destroy]

  # GET /delivery_boys
  # GET /delivery_boys.json
  def index
    @delivery_boys = DeliveryBoy.all
  end

  # GET /delivery_boys/1
  # GET /delivery_boys/1.json
  def show
    @assign_orders = @delivery_boy.orders.where(delivery_status: ['assign', 'Delivered','cancelled'])
  end

  # GET /delivery_boys/new
  def new
    @delivery_boy = DeliveryBoy.new
  end
  # GET /delivery_boys/1/edit
  def edit
  end

  # POST /delivery_boys
  # POST /delivery_boys.json
  def create
    @delivery_boy = DeliveryBoy.new(delivery_boy_params)

    respond_to do |format|
      if @delivery_boy.save
        format.html { redirect_to @delivery_boy, notice: 'Delivery boy was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_boy }
      else
        format.html { render :new }
        format.json { render json: @delivery_boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_boys/1
  # PATCH/PUT /delivery_boys/1.json
  def update
    respond_to do |format|
      if @delivery_boy.update(delivery_boy_params)
        format.html { redirect_to @delivery_boy, notice: 'Delivery boy was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_boy }
      else
        format.html { render :edit }
        format.json { render json: @delivery_boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_boys/1
  # DELETE /delivery_boys/1.json
  def destroy
    @delivery_boy.destroy
    respond_to do |format|
      format.html { redirect_to delivery_boys_url, notice: 'Delivery boy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def cancel_order
    @order = Order.find(params[:id])
    @order.delivery_status = "cancelled"
    @order.save
    respond_to do |format|
      format.html { redirect_to @order.delivery_boy, notice: "#{@order.name} is successfully cancelled" }
      format.json { render :show, status: :ok, location: @delivery_boy }
    end
  end
  def deliverd_order
    @order = Order.find(params[:id])
    @order.delivery_status = "Delivered"
    @order.save
    respond_to do |format|
      format.html { redirect_to @order.delivery_boy, notice: "#{@order.name} is successfully Delivered" }
      format.json { render :show, status: :ok, location: @delivery_boy }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_boy
      @delivery_boy = DeliveryBoy.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def delivery_boy_params
      params.require(:delivery_boy).permit(:name, :number, :address)
    end
end

app/helpers/delivery_boys_helper.rb
module DeliveryBoysHelper
end

app/views/delivery_boys/_form.html.erb
<%= form_with(model: delivery_boy, local: true) do |form| %>
  <% if delivery_boy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery_boy.errors.count, "error") %> prohibited this delivery_boy from being saved:</h2>

      <ul>
        <% delivery_boy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true%>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, required: true %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/delivery_boys/edit.html.erb
<h1>Editing Delivery Boy</h1>

<%= render 'form', delivery_boy: @delivery_boy %>

<%= link_to 'Show', @delivery_boy %> |
<%= link_to 'Back', delivery_boys_path %>

app/views/delivery_boys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Delivery Boys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delivery_boys.each do |delivery_boy| %>
      <tr>
        <td><%= delivery_boy.name %></td>
        <td><%= delivery_boy.number %></td>
        <td><%= delivery_boy.address %></td>
        <td><%= link_to 'Show', delivery_boy %></td>
        <td><%= link_to 'Edit', edit_delivery_boy_path(delivery_boy) %></td>
        <td><%= link_to 'Destroy', delivery_boy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery Boy', new_delivery_boy_path %> ||
<%= link_to 'View Orders', orders_path %>

app/views/delivery_boys/new.html.erb
<h1>New Delivery Boy</h1>

<%= render 'form', delivery_boy: @delivery_boy %>

<%= link_to 'Back', delivery_boys_path %>

app/views/delivery_boys/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @delivery_boy.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @delivery_boy.number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @delivery_boy.address %>
</p>

<%= link_to 'Edit', edit_delivery_boy_path(@delivery_boy) %> |
<%= link_to 'Back', delivery_boys_path %>

<h2>Orders List</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>customer_name</th>
      <th>Delivery_Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assign_orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.delivery_status %></td>
        <% if order.delivery_status == "assign" %>
      	  <td><%= link_to 'Mark as Deliver', deliverd_order_delivery_boy_path(order) %></td>
          <td style="display: inline-flex;" class="delievery_reason_form">
            <%= form_with(model: order, local: true) do |form| %>
              <div class="field">
                <%= form.label :delivery_reason %>
                <%= form.text_field :delivery_reason, required: true%>
              </div>
              <div class="field">
                <%= form.hidden_field :delivery_status, value: "cancelled"%>
              </div>
              <div class="actions">
                <%= form.submit "cancel order", class:"delivery_reason"%>
              </div>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %> 
  </tbody>
</table>