config/routes.rb
Rails.application.routes.draw do
  resources :projects, param: :slug
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' } 
  resources :delivery_boys do 
    member do
      get :cancel_order
      get 'deliverd_order',to: 'delivery_boys#deliverd_order'
    end
  end
  resources :orders do
    member do
      get :cancel_order
      get 'deliverd_order',to: 'orders#deliverd'
      post 'assign_order',to: 'orders#assign'
    end
  end
  resources :posts
  resources :authors
  resources :author_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  resources :comments
  resources :products do
    collection do
      get 'batch_operation'
    end
    member do
      get 'remove_description'
    end
  end
  resources :varients
end

app/models/order.rb
class Order < ApplicationRecord
  require 'csv'
  belongs_to :delivery_boy, optional: true
  #This method will call from orders.csv
  def self.custom_csv 
    CSV.generate do |csv|
      csv << ["id", "name", "address", "delivery_status", "customer_name", "delivery_reason"]
      all.each do |order|
        csv << [order.id, order.name, order.address, order.delivery_status, order.customer_name, order.delivery_reason]
        delivery_boy_fields = %w{id name number address}
        @db = order.delivery_boy
        csv << delivery_boy_fields
        csv << [@db.name, @db.number, @db.address]
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :cancel_order, :deliverd, :assign ]
  prepend_after_action :send_invoice, only: :deliverd
  prepend_before_action :set_cookie, only: :show
  # prepend_before_action :check_auth, only: :destroy
  # after_action :send_mail, only: :cancel_order
  def set_cookie
    puts "hello"
    # puts @order.as_json
    puts "-==-=-=-"
    puts "-==-=-=-"
    puts cookies[:name] = current_admin.name
    puts "-==-=-=-"
    puts "-==-=-=-"
  end
  def check_auth
    puts "--=-=---=-=-=-=-=-"
    puts "--=-=--check_auth method call-=-=-=-=-=-"
    puts "--=-=---=-=-=-=-=-"
  end
  def index
    @orders = Order.all
    @ordercounts =Order.group(:delivery_status).count
    respond_to do |format|
      format.html
      format.csv{ send_data @orders.custom_csv}
    end
  end

  def send_invoice
    puts "-==-=-=-"
    puts "-==-=-=-"
    puts "send method call"
    puts "send mail"
    puts "-==-=-=-"
    puts "-==-=-=-"
    puts "-==-=-=-"
  end
  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end
  def cancel_order
    @order.delivery_status = "cancelled"
    @order.save
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Order was successfully cancelled.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def deliverd
    @order.delivery_status = "Delivered"
    @order.save
    respond_to do |format|
      format.html { redirect_to orders_path, notice: "#{@order.name} was successfully Delivered." }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def assign
    @delivery_boy = DeliveryBoy.find(params[:delivery_boy_id])
    @assigned = @delivery_boy.orders << @order
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Order was successfully cancelled.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        if params[:order][:delivery_status] == "cancelled"
          @delivery_boy = Order.find(params[:id]).delivery_boy
          format.html { redirect_to @delivery_boy, notice: 'Order was successfully updated.' }
          format.json { render :show, status: :ok, location: @order }
        else
          format.html { redirect_to @order, notice: 'Order was successfully updated.' }
          format.json { render :show, status: :ok, location: @order }
        end
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:name, :address, :customer_name,:delivery_reason, :delivery_status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, required: true %>
  </div>
  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name, required: true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Report</h1>
<% @ordercounts.each do |status, count| %>
  <div style="display: inline-flex; ">
    <h3 style="padding-right:8px"><%= status %>:</h3> 
    <h3><%= count %></h3>
  </div>
<% end %>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>customer_name</th>
      <th>Delivery_Status</th>
      <th>Delivery boy name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Order.includes(:delivery_boy).each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.delivery_status %></td>
        <% if order.delivery_boy == nil %>
        <td> ---------- </td> 
        <% else %>
        <td><%= order.delivery_boy.name %></td>
        <% end %>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if order.delivery_status == "assign"%>
          <td>
            <%= link_to 'Mark as Deliver', deliverd_order_order_path(order)%>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Dowload Orders", orders_path(format: "csv") %> ||
<%= link_to 'New Order', new_order_path %> ||    
<%= link_to 'View Delivery Boys', delivery_boys_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>
<p>
  <strong>customer name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Delivery Status: </strong>
  <%= @order.delivery_status %>
</p>

<% if @order.delivery_status == "cancelled" %>
  <p>
    <strong>Delivery reason: </strong>
    <%= @order.delivery_reason %>
  </p>
<% end %>

<% if @order.delivery_status == "not assign" %>
  <div class="assign_boy">
    <p><strong>assing delivery boy:</strong></p>
    <%= form_tag assign_order_order_path do %>
      <%= select_tag 'delivery_boy_id', options_for_select(DeliveryBoy.all.collect{ |u| [u.name, u.id] }) %>
      <div class="actions">
        <%= submit_tag "ASSIGN", class:"submit_btn" %>
      </div>
      <% end %>
  </div>
<% end %>
<%= link_to 'Edit', edit_order_path(@order) %> ||
<%= link_to 'Back', orders_path %> 
<% if @order.delivery_status == "assign"%>
  <%= form_with(model: @order, local: true) do |form| %>
  <div class="field">
    <%= form.label :delivery_reason %>
    <%= form.text_field :delivery_reason, required: true%>
  </div>
  <div class="field">
    <%= form.hidden_field :delivery_status, value: "cancelled"%>
  </div>
  <div class="actions">
    <%= form.submit "cancel order", class:"delivery_reason"%>
  </div>
  <% end %>
 || <%#= link_to 'cancel', cancel_order_order_path(@order)%>
<% end %>