config/routes.rb
Rails.application.routes.draw do
  resources :projects, param: :slug
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' } 
  resources :delivery_boys do 
    member do
      get :cancel_order
      get 'deliverd_order',to: 'delivery_boys#deliverd_order'
    end
  end
  resources :orders do
    member do
      get :cancel_order
      get 'deliverd_order',to: 'orders#deliverd'
      post 'assign_order',to: 'orders#assign'
    end
  end
  resources :posts
  resources :authors
  resources :author_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  resources :comments
  resources :products do
    collection do
      get 'batch_operation'
    end
    member do
      get 'remove_description'
    end
  end
  resources :varients
end

app/models/product.rb
class Product < ApplicationRecord
  # has_many :pictures
  has_many :pictures, as: :imageable
  has_many :varients
  validates :creator, presence:{message: "can't blank"}
  def check_method(object)
    puts "this is association callback method=> before_add"
    puts object.as_json
  end
  # after_commit :bhadresh
  def bhadresh
    puts "=-=-=-=-=-=-=-=-=-=-=-"
    puts "=-=-=-=-=-=-=-=-=-=-=-"
    puts "=-=-=-=-=-=-=-=-=-=-=-"
    puts "=-=-=-=-=-=-=-=-=-=-=-"
    puts "=-=-=-=-=-=-=-=-=-=-=-"
    puts "=-=-=-=-=-=-=-=-=-=-=-"
    puts "=-=-=-=-=-=-=-=-=-=-=-"
    puts "=-=-=-=-=-=-=-=-=-=-=-"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :remove_description]
  before_action :hello, only: [:remove_description]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def hello
    puts "-==================-=-=-=-=--=-=-----=--=-="
    puts "-==================-=-=-=-=--=-=-----=--=-="
    puts "-==================-=-=-=-=--=-=-----=--=-="
    puts "-==================-=-=-=-=--=-=-----=--=-="
  end
  def remove_description
    @product.descrpition= nil
    @product.save
    redirect_to products_path
  end

  def batch_operation
    if params[:product_ids]
      @selectproduct = Product.where(id: params[:product_ids])
      @desc= ""
      @selectproduct.each do |p|
        @desc += p.descrpition
      puts "-==================-=-=-=-=--=-=-----=--=-="
      puts "-==================-=-=-=-=--=-=-----=--=-="
      puts "-==================-=-=-=-=--=-=-----=--=-="
      end
    @p= Product.create(descrpition: @desc)
    puts @p.as_json
    end
    if params[:product][:descrpition] != nil
      @desc =params[:product][:descrpition]
      puts "-====00-=--00-0-0"
      puts "-====00-=--00-0-0"
      @desc.as_json
      puts "-====00-=--00-0-0"
      puts "-====00-=--00-0-0"
      puts "-====00-=--00-0-0"
    end
    redirect_to products_path
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:creator, :descrpition, :picture)
      # params.require(:product).permit(:title, :creator)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
    <%#= form_with model: product do |product| %>
    <%#= product.text_field :name %>
    <%#= fields_for :varient, product.varients do |contact_detail_form| %>
    <%#= contact_detail_form.text_field :phone_number %>
    <%# end %>
    <%# end %>

    <%= form_with model: product, url: products_path ,local: true do |f| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
      </div>
    <%= f.text_field :creator%>
    <%= f.label :creator %>
    <%= f.label :status%>
    <%#= f.select :status, ["hello", "bjbhjbjhb"], include_blank: "select status" %>
    <!-- <%#= f.time_zone_select :time_zone %> -->
    <%#= f.select :time_zone, Post.statuses, include_blank: "select status"  %>
    <%= f.date_select :birth_date %>
    <%#= f.select :time_zone, options_for_select(Post.statuses)%>
    <%#= select_tag "hello"  %>
    <%= f.select :name, options_for_select(Book.order(:price).pluck(:title, :id), :id), multiple: true %>
    <%= f.collection_select :name, Book.order(:price), :id, :title, multiple: true  %>
    <%= f.label :language %>
    <%#= f.check_box :english %>
    <%#= f.check_box :hindi %>
    <%# Post.all.each do |c| %>
        <%#= check_box_tag "post_ids[#{c.id}]", c.id, :name => "car_ids[]" %>
    <%# end %>
    <%#= f.collection_check_boxes :creator, Post.order(:title), :id, :title %>  
    <%#= f.collection_check_boxes :creator, @post_status, @post_status.each {|v| puts v.first} %>
    <%= f.file_field :picture, multiple: true, accept: 'image/jpeg, image/png '%>
    <%#= f.collection_radio_buttons :id, Post.order(:title), :id, :title %>
    <%#= f.collection_check_boxes :creator, Product.order(:creator), :id, :creator %>
    <%#= f.select :creator, [["helo", "hi"],["helo", "ho"],["helo", "kk"]] %>
    <%#= f.collection_check_boxes :creator, Product.order(:creator), :id, :creator %>
    <%#= f.collection_radio_buttons :id, Product.order(:creator), :id, :creator %>
    

    <!-- #not --> 
    <%#= form_with model: Post do |form| %>
        <%#= text_field_with_label form, :title %>
    <%# end %>
    

    <!-- How it works? -->
    <%#= form_with model: @person do |person_form| %>
        <%#= person_form.text_field :name %>
        <%# @person.addresses.each do |address| %>
            <%#= person_form.fields_for address, index: address.id do |address_form| %>
                <%#= address_form.text_field :city %>
            <%# end %>
        <%# end %>
    <%# end %>


    <%= f.submit "add product"%>
    <% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>

<%= form_tag batch_operation_products_path, method: :get do %>
  <table>
    <thead>
      <tr>
        <!-- <th>Title</th>
        <th>Creator</th> -->
        <th></th>
        <th></th>
        <th>creator</th>
        <th>description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>    
        <tr>
          <% if product.descrpition != nil  %>
            <td><%= check_box_tag "product_ids[]", product.id ,false %></td>
            <td><%= link_to "remove description", remove_description_product_path(product)%></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= product.creator %></td>
          <% if product.descrpition == nil%>
            <td class="delievery_reason_form" style="display: flex;">
            <%= form_with(model: product, local: true) do |form| %>
              <div class="field">
                <%= form.label :descrpition %>
                <%= form.text_field :descrpition %>
              </div>
              <div class="actions">
                <%= form.submit 'add description', class:"delivery_reason"%>
              </div>
              <% end %>
            </td>
            <% else %>
              <td> <%= product.descrpition %></td>
          <% end %>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag 'create new record', name: nil %>
<% end %>
<br>

<%= link_to 'New Product', new_product_path %> ||
<%= link_to 'view Varients', varients_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>description:</strong>
  <%= @product.descrpition %>
</p>
<p>
  <strong>Title:</strong>
  <%= @product.creator %>
</p>

<p>
  <!-- <strong>Creator:</strong> -->
  <%#= @product.creator %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>