config/routes.rb
Rails.application.routes.draw do
  resources :projects, param: :slug
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' } 
  resources :delivery_boys do 
    member do
      get :cancel_order
      get 'deliverd_order',to: 'delivery_boys#deliverd_order'
    end
  end
  resources :orders do
    member do
      get :cancel_order
      get 'deliverd_order',to: 'orders#deliverd'
      post 'assign_order',to: 'orders#assign'
    end
  end
  resources :posts
  resources :authors
  resources :author_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  resources :comments
  resources :products do
    collection do
      get 'batch_operation'
    end
    member do
      get 'remove_description'
    end
  end
  resources :varients
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>

  </head>

  <body>
    <div id="user_nav">
      <% if admin_signed_in? %>
          Signed in as <%= current_admin.email %>
          <%= link_to 'Sign out', destroy_admin_session_path, method: :delete %>
      <% else %>
          <%= link_to 'Register', new_admin_registration_path %> or <%= link_to 'Sign in', new_admin_session_path %>
      <% end %>
    </div>
     <p><%= flash[:notice] %></p>
     <p><%= flash[:alert] %></p>
    <%= yield %>

  </body>
</html>